### ISSUE TITLE
Help?

### ISSUE THREAD

**Issue by Romaoplays** [Lazersmoke/Botanical-Workshop#2]
Whats the website for the mod so i can see what thinks are added by it? :)

**Comment by Lazersmoke** [comment]
There isn't one. I'm still planning how and where and when it will be released. When it is released there will probably be a features list, and everything will have a lexicon entry.

**Comment by Lazersmoke** [comment]
@romaoplys you can play the first build now https://github.com/Lazersmoke/Botanical-Workshop/raw/master/jars/BotanicalWorkshop%20r0.1-6.jar

needs PlayerAPI and Botania
